import fs from "fs";
// Pixel football on a W x H cell grid. Returns rects in a group centred at 0,0.
function ball(cell, opts = {}) {
  const W = 24, H = 13;
  // Half-widths per row, set by hand: a lens with real points, not an
  // ellipse rounded into a barrel.
  const rows = [3, 6, 8, 10, 11, 12, 12, 12, 11, 10, 8, 6, 3];
  const px = (c, r, fill) => `<rect x="${(c * cell).toFixed(0)}" y="${(r * cell).toFixed(0)}" width="${cell}" height="${cell}" fill="${fill}"/>`;
  const out = [];
  const ox = -W / 2, oy = -H / 2;
  const inBall = (c, r) => r >= 0 && r < H && Math.abs(c + 0.5) <= rows[r];
  // outline: any cell outside the ball that touches it
  for (let r = -1; r <= H; r++) for (let c = -13; c < 13; c++) {
    if (inBall(c, r)) continue;
    if ([[1,0],[-1,0],[0,1],[0,-1],[1,1],[-1,-1],[1,-1],[-1,1]].some(([dc, dr]) => inBall(c + dc, r + dr))) out.push(px(c, r + 0, opts.outline));
  }
  for (let r = 0; r < H; r++) for (let c = -rows[r]; c < rows[r]; c++) {
    let fill = r < 3 ? opts.hi : r > 9 ? opts.lo : opts.mid;
    const absc = Math.abs(c + 0.5);
    // end stripes
    if ((absc >= 7.5 && absc <= 8.5) && r >= 3 && r <= 9) fill = opts.lace;
    // laces: centre line with ticks
    if (r === 6 && absc <= 3.5) fill = opts.lace;
    if ((r === 5 || r === 7) && [0.5, 2.5].includes(absc)) fill = opts.lace;
    out.push(px(c, r, fill));
  }
  return `<g transform="translate(${-0} ${-0})" shape-rendering="crispEdges"><g transform="translate(0 ${(oy * cell).toFixed(0)})">${out.join("")}</g></g>`;
}
const P = { outline: "#12002b", hi: "#e0703a", mid: "#c9581f", lo: "#8e3a12", lace: "#fff6e6" };
const big = `<!-- Home screen icon. The football is the subject: three quarters of
     the width, a dark outline so it separates from the sun behind it, and
     white laces and stripes that survive a 60px crop. Sun and grid stay as
     the app's backdrop. Everything that matters sits inside the middle
     80% so a maskable circle crop cannot cut the ball.
     Generated by a script; edit the palette or the sprite there. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <defs>
    <linearGradient id="sky" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#12002b"/><stop offset="50%" stop-color="#2b0546"/><stop offset="78%" stop-color="#4a0b55"/><stop offset="100%" stop-color="#1a0332"/>
    </linearGradient>
    <linearGradient id="sun" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#ffe45e"/><stop offset="40%" stop-color="#ff9d3d"/><stop offset="75%" stop-color="#ff2079"/><stop offset="100%" stop-color="#c13cff"/>
    </linearGradient>
    <mask id="slots">
      <rect width="1024" height="1024" fill="#fff"/>
      <rect x="0" y="560" width="1024" height="22" fill="#000"/>
      <rect x="0" y="612" width="1024" height="30" fill="#000"/>
      <rect x="0" y="672" width="1024" height="40" fill="#000"/>
    </mask>
  </defs>
  <rect width="1024" height="1024" fill="url(#sky)"/>
  <circle cx="512" cy="470" r="330" fill="url(#sun)" mask="url(#slots)"/>
  <g stroke="#05d9e8" fill="none">
    <line x1="0" y1="800" x2="1024" y2="800" stroke-width="7" opacity=".9"/>
    <g stroke-width="5" opacity=".38">
      <line x1="512" y1="800" x2="-200" y2="1024"/><line x1="512" y1="800" x2="150" y2="1024"/><line x1="512" y1="800" x2="512" y2="1024"/><line x1="512" y1="800" x2="874" y2="1024"/><line x1="512" y1="800" x2="1224" y2="1024"/>
      <line x1="0" y1="850" x2="1024" y2="850"/><line x1="0" y1="930" x2="1024" y2="930"/>
    </g>
  </g>
  <g transform="translate(512 500)">${ball(32, P)}</g>
</svg>`;
const small = `<!-- The 16 and 32 pixel favicons: the same football, no grid, filling the square. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <defs><linearGradient id="sun2" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#ffe45e"/><stop offset="55%" stop-color="#ff9d3d"/><stop offset="100%" stop-color="#ff2079"/></linearGradient></defs>
  <rect width="1024" height="1024" fill="#2b0546"/>
  <circle cx="512" cy="512" r="470" fill="url(#sun2)"/>
  <g transform="translate(512 512)">${ball(38, P)}</g>
</svg>`;
fs.writeFileSync("icons/icon.svg", big);
fs.writeFileSync("icons/icon-small.svg", small);
console.log("written");
